services:
  - type: web
    name: smart-ai-trading-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_dashboard.py --server.port=10000 --server.address=0.0.0.0
    autoDeploy: true
