[EMAIL]
EMAIL_FROM = "tradingstrategieswithram@gmail.com"
EMAIL_ADDRESS = "tradingstrategieswithram@gmail.com"
EMAIL_PASSWORD = "mslbfcbkxizqjfeb"
EMAIL_TO = "tradingstrategieswithram@gmail.com"

[ALERTS]
TELEGRAM_TOKEN = "7708322009:AAG93GiPprOI827RW1We5AjvlCE7wRFjGwA"
TELEGRAM_CHAT_ID = "1367429867"